export enum SagaActions {
  FETCH_BREWS = 'FETCH_BREWS',
  DELETE_BREW = 'DELETE_BREW',
  LIKE_BREW = 'LIKE_BREW',
  ADD_BREW = 'ADD_BREW',
  EDIT_BREW = 'EDIT_BREW',
  FETCH_COFFEES = 'FETCH_COFFEES',
  FETCH_ONE_COFFEE = 'FETCH_ONE_COFFEE',
  SET_BREWING_OR_FAV = 'SET_BREWING_OR_FAV',
  DELETE_COFFEE = 'DELETE_COFFEE',
  ADD_COFFEE = 'ADD_COFFEE',
}
