#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

echo "${CYAN}→${NO_COLOR} Running TypeScript compiler check..." && npx tsc -p base.tsconfig.json && echo "${GREEN}Success! Pushing commit...${NO_COLOR}"
