#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

if [ -n "$(git status --porcelain -- '*.ts' '*.tsx')" ]; then
    echo "${CYAN}→${NO_COLOR} Running TypeScript compiler check..."
    npx tsc -p src/server/tsconfig.json & npx tsc -p src/client/tsconfig.json
fi

echo "${CYAN}→${NO_COLOR} Running lint-staged..."
npx lint-staged
echo "${GREEN}Success!${NO_COLOR}"
